### ISSUE TITLE
Definite Issue With Pods Running Before CRDs Available

### ISSUE THREAD

**Issue by dgoodwin** [openshift/machine-api-operator#104]
On a new cluster from openshift-install this morning I ended up no worker nodes. I had the expected MachineSets, but no Machines.

```
$ klf clusterapi-manager-controllers-68d86f58b6-kgpck controller-manager                                             
2018/10/24 11:30:18 Registering Components.
2018/10/24 11:30:18 Starting the Cmd.
E1024 11:30:18.217697       1 controller.go:231] unable to create a machine = , due to machines.cluster.k8s.io "dgoodwin1-worker-0-t5tjm" is forbidden: cannot set blockOwnerDeletion
 in this case because cannot find RESTMapping for APIVersion cluster.k8s.io/v1alpha1 Kind MachineSet: no matches for kind "MachineSet" in version "cluster.k8s.io/v1alpha1"         
E1024 11:30:18.229702       1 controller.go:231] unable to create a machine = , due to machines.cluster.k8s.io "dgoodwin1-worker-1-wlbt4" is forbidden: cannot set blockOwnerDeletion
 in this case because cannot find RESTMapping for APIVersion cluster.k8s.io/v1alpha1 Kind MachineSet: no matches for kind "MachineSet" in version "cluster.k8s.io/v1alpha1"         
E1024 11:30:18.303835       1 controller.go:231] unable to create a machine = , due to machines.cluster.k8s.io "dgoodwin1-worker-2-wnjds" is forbidden: cannot set blockOwnerDeletion
 in this case because cannot find RESTMapping for APIVersion cluster.k8s.io/v1alpha1 Kind MachineSet: no matches for kind "MachineSet" in version "cluster.k8s.io/v1alpha1"         
E1024 11:30:18.337241       1 controller.go:231] unable to create a machine = , due to machines.cluster.k8s.io "dgoodwin1-worker-0-n64h9" is forbidden: cannot set blockOwnerDeletion
 in this case because cannot find RESTMapping for APIVersion cluster.k8s.io/v1alpha1 Kind MachineSet: no matches for kind "MachineSet" in version "cluster.k8s.io/v1alpha1"         
E1024 11:30:18.339724       1 controller.go:231] unable to create a machine = , due to machines.cluster.k8s.io "dgoodwin1-worker-1-g5dt8" is forbidden: cannot set blockOwnerDeletion
 in this case because cannot find RESTMapping for APIVersion cluster.k8s.io/v1alpha1 Kind MachineSet: no matches for kind "MachineSet" in version "cluster.k8s.io/v1alpha1"         
E1024 11:30:18.342185       1 controller.go:231] unable to create a machine = , due to machines.cluster.k8s.io "dgoodwin1-worker-2-lbndq" is forbidden: cannot set blockOwnerDeletion
 in this case because cannot find RESTMapping for APIVersion cluster.k8s.io/v1alpha1 Kind MachineSet: no matches for kind "MachineSet" in version "cluster.k8s.io/v1alpha1" 
```

The pod appears to have started running before the MachineSet API was registered? However MachineSets did exist, just no Machines. I deleted this pod above and let the deployment recreate it, and immediately my worker Machine's were created, indicating a resync would have fixed the issue whenever it occurred. (10 minutes?)

**Comment by crawford** [comment]
I just ran into this as well on libvirt. Sure enough, deleting the controllers pod caused everything to come up.

**Comment by smarterclayton** [comment]
I hit this today, after deleting the controllerer pod I started getting:

```
yup, that was it

```
2018/11/12 17:13:51 Starting the Cmd.
E1112 17:13:52.291318       1 controller.go:370] <nil>
E1112 17:13:52.398532       1 controller.go:370] <nil>
E1112 17:13:52.505595       1 controller.go:370] <nil>
```

That fixed it though (the logging looks spurious)

**Comment by sallyom** [comment]
I hit this, too, in AWS.  `openshift-install` completed successfully, bootstrap node was terminated but on closer inspection only 3 master instances were running in aws.  To fix I `oc delete pod clusterapi-manager-controllers-xxxxxblah -n openshift-cluster-api`  The controller pod deletion caused a recreate, and 3 worker instances were started/joined the cluster, then cluster was healthy.

**Comment by smarterclayton** [comment]
once I killed the operator about 2-3 minutes

**Comment by sallyom** [comment]
same, a few minutes

**Comment by galletti94** [comment]
Hmm. I guess something else must be going on for me then. I am seeing the worker machines but not the worker nodes... The log of the machine-controller keeps displaying the following in a loop:
```
I1112 19:01:56.093401       1 controller.go:113] Running reconcile Machine for master0
I1112 19:01:56.093453       1 actuator.go:163] Checking if machine master0 for cluster test1 exists.
I1112 19:01:56.094730       1 domain.go:427] Created libvirt connection: 0xc42000e908
I1112 19:01:56.094774       1 domain.go:628] Check if "master0" domain exists
I1112 19:01:56.095070       1 domain.go:44] Closing libvirt connection: 0xc42000e908
I1112 19:01:56.095302       1 controller.go:163] Reconciling machine object master0 triggers idempotent update.
I1112 19:01:56.095346       1 actuator.go:137] Updating machine master0 for cluster test1.
I1112 19:01:56.096356       1 domain.go:427] Created libvirt connection: 0xc4200e69f8
I1112 19:01:56.096405       1 domain.go:613] Lookup domain by name: "master0"
I1112 19:01:56.096645       1 actuator.go:258] Updating status for master0
I1112 19:01:56.097116       1 actuator.go:305] Machine master0 status has changed, updating
I1112 19:01:56.296066       1 domain.go:44] Closing libvirt connection: 0xc4200e69f8
I1112 19:01:56.296492       1 controller.go:113] Running reconcile Machine for test1-worker-0-8n756
I1112 19:01:56.296561       1 actuator.go:163] Checking if machine test1-worker-0-8n756 for cluster test1 exists.
I1112 19:01:56.298448       1 domain.go:427] Created libvirt connection: 0xc42000e968
I1112 19:01:56.298531       1 domain.go:628] Check if "test1-worker-0-8n756" domain exists
I1112 19:01:56.298801       1 domain.go:44] Closing libvirt connection: 0xc42000e968
I1112 19:01:56.299116       1 controller.go:163] Reconciling machine object test1-worker-0-8n756 triggers idempotent update.
I1112 19:01:56.299235       1 actuator.go:137] Updating machine test1-worker-0-8n756 for cluster test1.
I1112 19:01:56.300310       1 domain.go:427] Created libvirt connection: 0xc42000e980
I1112 19:01:56.300370       1 domain.go:613] Lookup domain by name: "test1-worker-0-8n756"
I1112 19:01:56.300685       1 actuator.go:258] Updating status for test1-worker-0-8n756
I1112 19:01:56.301292       1 actuator.go:305] Machine test1-worker-0-8n756 status has changed, updating
I1112 19:01:56.521073       1 domain.go:44] Closing libvirt connection: 0xc42000e980
```

**Comment by benjaminapetersen** [comment]
I hit this as well, but was not able to do what @sallyom did to fix.  `oc get pods -n openshift-cluster-api` revealed no pods.  I should have copied the output here before I hacked things up.  I'm going to delete/recreate my cluster and will post better information if I continue to experience the same problem.

**Comment by gbraad** [comment]
currently hitting this on my local libvirt install. the master is up, the communication with libvirt is possible (`nc 192.168.126.1 16509` connects), DNS resolves, also deleted the pod as described, but nothing happens. rebooted and did the same again... how can I inspect the logs? The RBAC prevents me to get the logs (`forbidden: User "system:node:test1-master-0"cannot get pods/log in the namespace "openshift-cluster-api": no RBAC policy matched`)

**Comment by enxebre** [comment]
I haven't been able to reproduce this. We've moved CRDs generation up to CVO https://github.com/openshift/machine-api-operator/pull/127 so assuming this was somehow a race issue it shouldn't happen anymore. This ticket is to track the original issue described by dgoodwin above so please make sure you verify it by running the same command and seeing the same logs he pasted in the description. You can use the admin kubeconfig generated by the installer within the `auth/` folder

**Comment by enxebre** [comment]
Closing this due not being able to reproduce. Please reopen if you see this happening again.

**Comment by anildhingra** [comment]
get same error again

I group "" in the namespace "openshift-machine-api"' (will not retry!)
I0301 04:46:35.651096       1 controller.go:114] Running reconcile Machine for test-qmt5x-worker-0-t8hpf
I0301 04:46:35.651274       1 actuator.go:205] Checking if machine test-qmt5x-worker-0-t8hpf exists.
I0301 04:46:35.656355       1 client.go:131] Created libvirt connection: 0xc4202aa130
I0301 04:46:35.656387       1 client.go:264] Check if "test-qmt5x-worker-0-t8hpf" domain exists
I0301 04:46:35.656694       1 client.go:140] Closing libvirt connection: 0xc4202aa130
I0301 04:46:35.657012       1 controller.go:184] Reconciling machine object test-qmt5x-worker-0-t8hpf triggers idempotent create.
I0301 04:46:35.657038       1 actuator.go:112] Creating machine "test-qmt5x-worker-0-t8hpf"
I0301 04:46:35.658982       1 client.go:131] Created libvirt connection: 0xc4202aa148
I0301 04:46:35.659032       1 client.go:332] Create a libvirt volume with name test-qmt5x-worker-0-t8hpf for pool default from the base volume /var/lib/libvirt/images/test-qmt5x-base
E0301 04:46:35.660725       1 actuator.go:106] Machine error: error creating volume Can't retrieve volume /var/lib/libvirt/images/test-qmt5x-base
E0301 04:46:35.660744       1 actuator.go:50] test-qmt5x-worker-0-t8hpf: error creating libvirt machine: error creating volume Can't retrieve volume /var/lib/libvirt/images/test-qmt5x-base
I0301 04:46:35.660751       1 client.go:140] Closing libvirt connection: 0xc4202aa148
W0301 04:46:35.661079       1 controller.go:186] unable to create machine test-qmt5x-worker-0-t8hpf: test-qmt5x-worker-0-t8hpf: error creating libvirt machine: error creating volume Can't retrieve volume /var/lib/libvirt/images/test-qmt5x-base
E0301 04:46:35.668291       1 event.go:203] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test-qmt5x-worker-0-t8hpf.1587bc2f0b7c8999", GenerateName:"", Namespace:"openshift-machine-api", SelfLink:"", UID:"", ResourceVersion:"12508", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"Machine", Namespace:"openshift-machine-api", Name:"test-qmt5x-worker-0-t8hpf", UID:"d06a646e-3bda-11e9-a6d2-664f163f5f0f", APIVersion:"machine.openshift.io/v1beta1", ResourceVersion:"6091", FieldPath:""}, Reason:"FailedCreate", Message:"CreateError", Source:v1.EventSource{Component:"libvirt-controller", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63687012306, loc:(*time.Location)(0x1eb0f20)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf164c2ae761a0bf, ext:89237827762, loc:(*time.Location)(0x1eb0f20)}}, Count:15, Type:"Warning", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "test-qmt5x-worker-0-t8hpf.1587bc2f0b7c8999" is forbidden: User "system:serviceaccount:openshift-machine-api:default" cannot patch resource "events" in API group "" in the namespace "openshift-machine-api"' (will not retry!)
