### ISSUE TITLE
support huaweicloud

### ISSUE THREAD

**Issue by setoru** [openshift/machine-api-operator#1221]
Hi,

I'm trying to use HuaweiCloud in OpenShift, However,it seems it's not supported right now. I'd like to add HuaweiCloud support myself, but I'm not quite sure how to go about it. Specifically, I want to integrate it and make sure it works smoothly with clusterAutoscaler.

Could you please guide me on the steps? Do I only need to integrate machine-api-provider, or are there other repositories I should consider? And how do I ensure it's all up and running?

Thanks!

**Comment by setoru** [comment]
Do I need to integrate openshift/installer first

**Comment by elmiko** [comment]
integrating a new cloud provider directly into openshift is a complex task, i would advise looking towards cluster-api and the future of the external platform on openshift. i would expect that in the future you will be able to cluster-api to integrate a huawei cloud provider. i would start with creating a cluster-api provider first.

these docs capture the general process for adding a new cloud provider to openshift, http://docs.providers.openshift.org/

you would most likely need to carry any patches for your work locally as we are not accepting new providers into machine-api. i would focus efforts on creating a cluster-api provider.
