### ISSUE TITLE
Assign a priority class to pods

### ISSUE THREAD

**Issue by aveshagarwal** [openshift/machine-api-operator#143]
Priority classes docs:
https://docs.openshift.com/container-platform/3.11/admin_guide/scheduling/priority_preemption.html#admin-guide-priority-preemption-priority-class

Example: https://github.com/openshift/cluster-monitoring-operator/search?q=priority&unscoped_q=priority

Notes: The pre-configured system priority classes (`system-node-critical` and `system-cluster-critical`) can only be assigned to pods in `kube-system` or `openshift-*` namespaces. Most likely, core operators and their pods should be assigned `system-cluster-critical`. Please do not assign `system-node-critical` (the highest priority) unless you are really sure about it.

**Comment by enxebre** [comment]
fixed by https://github.com/openshift/machine-api-operator/pull/230 and https://github.com/openshift/machine-api-operator/pull/229
