### ISSUE TITLE
Add bare-metal actuator

### ISSUE THREAD

**Issue by cynepco3hahue** [openshift/machine-api-operator#149]
Hi guys,
I want to integrate our work on the bare metal actuator(runs fencing commands via IPMI) to `machine-api-operator`, but currently we only fence existing nodes without provisioning support, because of it I have trouble to implement bootstrapping logic under `baremetal-actuator` CLI(similar to https://github.com/openshift/cluster-api-provider-libvirt/blob/d82d0107b90324aa38ea23b132bae8b8da67b3bb/cmd/libvirt-actuator/main.go#L174).

So I want to know if it a hard requirement for integration and if you have some other requirements from the actuator I also like to hear them.

Link on bare metal actuator - https://github.com/kubevirt/cluster-api-provider-external

**Comment by enxebre** [comment]
let's track this in https://github.com/openshift/machine-api-operator/issues/245
