### ISSUE TITLE
Support scaling down to 0

### ISSUE THREAD

**Issue by pierreozoux** [openshift/machine-api-operator#182]
Related to #181 we'll need also to be able to scale down to 0 :)

**Comment by enxebre** [comment]
One potential solution will be leveraging machineClasses for this https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/apis/cluster/v1alpha1/machineclass_types.go#L51-L56. please reopen against https://github.com/openshift/kubernetes-autoscaler if relevant
