### ISSUE TITLE
Duplicate credentialsrequests

### ISSUE THREAD

**Issue by mjudeikis** [openshift/machine-api-operator#328]
Last 2 credentials are being provisioned on Azure cluster with AzurePlatform as provider
.
```
[mjudeiki@redhat openshift-azure]$ oc get credentialsrequests.cloudcredential.openshift.io 
NAME                               AGE
azure-openshift-ingress            161m
cloud-credential-operator-iam-ro   161m
openshift-image-registry           161m
openshift-ingress                  161m

openshift-machine-api              161m
openshift-machine-api-azure        161m
```
One of them is OpenStack:
```
[mjudeiki@redhat openshift-azure]$ oc get credentialsrequests.cloudcredential.openshift.io openshift-machine-api -o yaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  creationTimestamp: "2019-06-17T10:22:45Z"
  finalizers:
  - cloudcredential.openshift.io/deprovision
  generation: 48
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api
  namespace: openshift-cloud-credential-operator
  resourceVersion: "84721"
  selfLink: /apis/cloudcredential.openshift.io/v1/namespaces/openshift-cloud-credential-operator/credentialsrequests/openshift-machine-api
  uid: d8c61b45-90e9-11e9-bbff-000d3a18e198
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: OpenStackProviderSpec
  secretRef:
    name: openstack-cloud-credentials
    namespace: openshift-machine-api
status:
  lastSyncGeneration: 48
  lastSyncTimestamp: "2019-06-17T12:57:45Z"
  provisioned: true
```

```
[mjudeiki@redhat openshift-azure]$ oc get credentialsrequests.cloudcredential.openshift.io openshift-machine-api-azure -o yaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  creationTimestamp: "2019-06-17T10:23:02Z"
  finalizers:
  - cloudcredential.openshift.io/deprovision
  generation: 1
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-azure
  namespace: openshift-cloud-credential-operator
  resourceVersion: "2160"
  selfLink: /apis/cloudcredential.openshift.io/v1/namespaces/openshift-cloud-credential-operator/credentialsrequests/openshift-machine-api-azure
  uid: e30e41bf-90e9-11e9-bbff-000d3a18e198
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    roleBindings:
    - role: passthrough
      scope: resourcegroup
  secretRef:
    name: azure-cloud-credentials
    namespace: openshift-machine-api
```

I suspect all file is being evaluated and because 2 last does not overwrite each other we get multiple credentials. 
Should they contain all Cloud provider credentials like this? Where is the logic personalize and evaluate only required file to be created? 

/cc  @ingvagabund @enxebre @abhinavdahiya @mandre

**Comment by enxebre** [comment]
@dgoodwin is the name of the credRequest relevant for the ca-operator filtering per platform https://github.com/openshift/machine-api-operator/blob/master/install/0000_30_machine-api-operator_00_credentials-request.yaml#L39-L57?
Is an expectation for them to be named the same i.e move`openshift-machine-api-azure` to `openshift-machine-api`?

**Comment by dgoodwin** [comment]
I don't think the name matters, ideally I'd like to see them contain the cloud provider in the name. The plan thus far is for the release image to deliver a credentials request for every supported cloud platform. The cred operator detects it's platform on startup and should no-op on any cred requests that are not for that platform.

**Comment by mjudeikis** [comment]
Are we saying we will be deploying all requests for all platforms for all componetns to all clusters and leave credentials operators to "sort itself out"?

**Comment by dgoodwin** [comment]
Correct. The goal was to give teams control of their creds in their component repos, but they need to be assembled into the release image as a central location for auditing purposes. There is only one release image not one per cloud and thus we expect to deploy cred requests for supported clouds and skip those that are not relevant.

**Comment by mjudeikis** [comment]
I don't think this is right way to do this. At the moment I see AWS CredentialsRequests in my Azure cluster. The same code base will be used to deploy managed Openshift cluster on Azure and AWS, in the future other cloud providers. 

Now as an Azure customer I don't want to see any reference to AWS. Considering some of these services will be First party services for their clouds and sold by cloud X people only to cloud X customers. 

In the example on my Azure cluster I see:
```
  providerSpec:                                                                                
    apiVersion: cloudcredential.openshift.io/v1                                                
    kind: AWSProviderSpec                                                                      
    statementEntries:                                                                          
    - action:                                                                                  
      - iam:GetUser                                                                            
      - iam:GetUserPolicy                                                                      
      - iam:ListAccessKeys                                                                     
      effect: Allow                                                                            
      resource: '*'                                                                            
  secretRef:                                                                                   
    name: cloud-credential-operator-iam-ro-creds                                               
    namespace: openshift-cloud-credential-operator                                             
status:                                                                                                                                                                                                                                                                                                                                                                                                                              
```

We need a way to evaluate and deliver only required CredentialRequests for each Operator/Platform because 1st - its does not look nice. 2nd - with 4+ cloud providers - it's noisy. 3rd. We cant just fire all othe cluster and hope for the best. At some point, somebody created a cloud with 2 credentials providers and we will get all these "provisioned".

We should keep this to bare minimum and not just fire everything into the cluster and let it sort itself out.

**Comment by dgoodwin** [comment]
@mjudeikis can you file an issue at https://github.com/openshift/cloud-credential-operator, we will clarify the complications involves and get PM to take a look for prioritization.
