### ISSUE TITLE
Node Controller link broken in README.md

### ISSUE THREAD

**Issue by Jamstah** [openshift/machine-api-operator#444]
There's a link to the Node Controller in the README, that link goes to a 404.

I don't know the history, so maybe this just needs removing? Or updating to something else?

**Comment by elmiko** [comment]
i looked around the main readme but i didn't see the link you were talking about. which readme file is this in, could you give a reference link with the file number?

**Comment by Jamstah** [comment]
It was there when I raised it :)

https://github.com/openshift/machine-api-operator/blob/829aed455755535b778f8ab298fd3c86c79dfb13/README.md

README doesn't include that link any more.

**Comment by elmiko** [comment]
no worries, thanks for closing the issue!
