### ISSUE TITLE
cluster-api 

### ISSUE THREAD

**Issue by lelvisl** [openshift/machine-api-operator#612]
Is this project compatible with https://github.com/kubernetes-sigs/cluster-api?

**Comment by enxebre** [comment]
This operator focuses on `machine.openshift.io` machine management within the OCP context, e.g it assumes a [cluster version operator](https://github.com/openshift/cluster-version-operator) for [installing resources](https://github.com/openshift/machine-api-operator/tree/master/install).

`machine.openshift.io/v1beta1` is heavily based on the v1alpha1 cluster API machine/machineSet types. This project and cluster api share multiple commonalities for automated Machine management e.g machineSets, machineHealthChecking, autoscaler...

It's not an immediate goal atm to enable the machine api operator to run the x-k8s.cluster.io machine API. When that API become beta this might be reconsidered.
