### ISSUE TITLE
[vSphere] Hashed machine names not working with external load balancer and ingress

### ISSUE THREAD

**Issue by jomeier** [openshift/machine-api-operator#658]
Hi,

in our setup we have an external load balancer (Citrix Netscaler) before our OpenShift 4.5 cluster on vSphere.

If we add a new Machine (increasing MachineSet by 1) in OpenShift, a new VM is created in vSphere where the name of the VM consists of the MachineSet name and a random string hash e.g.: "workers-sdfsda".

If one of the ingress pods is scheduled to this new VM, the problem is that the hostname of this VM is not in the backend pool of our external loadbalancer. This ingress can't be reached through the load balancer afterwards.

Is it possible to use a naming scheme for the ephemeral workers created by the machine-api-operator that looks like this:

\<NAME OF MACHINESET\>-[1 ... 1000]

We could add these hostnames to our external load balancers backend pool in advance and then placing ingress pods to the ephemeral workers would work out of the box.

Thanks and greetings,

Josef

**Comment by abhinavdahiya** [comment]
I think you will be better suited to writer a connector that can go from `ready nodes` => `lb backend pool manager`
