### ISSUE TITLE
MachineHealthCheck fights with MachineSet on invalid configuration

### ISSUE THREAD

**Issue by zaneb** [openshift/machine-api-operator#736]
The enhancement doc for the Machine lifecycle [states](https://github.com/openshift/enhancements/blob/master/enhancements/machine-api/machine-instance-lifecycle.md#failed) that a Machine will move to the `Failed` phase if there is an error in the Machine configuration that precludes trying to create a provider.

The MachineHealthCheck controller will [immediately delete](https://github.com/openshift/machine-api-operator/blob/release-4.6/pkg/controller/machinehealthcheck/machinehealthcheck_controller.go#L560-L564) any Machine in the `Failed` phase. On platforms that put Machines into the `Failed` phase due to invalid configuration, this will result in a fight with the MachineSet controller, constantly creating and deleting Machines.

The following actuators are affected:
* AWS
* Azure
* GCP
* OpenStack
* libvirt
* oVirt
* kubevirt
* kubemark

The vSphere actuator won't display this behaviour until #735 is merged.
The baremetal (Metal³) actuator doesn't currently return InvalidConfiguration errors, but this is planned for the future.

A solution to this might be for the MachineHealthCheck to not queue failed Machines for immediate deletion in the case where the ErrorReason is `InvalidConfiguration`, and instead only delete them after a timeout. One obstacle to this is that the ErrorReason is not currently recorded by the Machine controller. That will be fixed by #701.

**Comment by JoelSpeed** [comment]
We discussed an issue very similar to this yesterday during backlog grooming.

We discussed several ideas during that call:

1. Introduce some sort of backoff mechanism
    The MHC controller would keep track of when it had last remediated a machine from a particular MHC and try to detect hot loops and back-off. This is technically complex and would be tough to implement.

2. Introduce a `minimumAge` (name TBC) field to the MHC
    The MHC would wait until the Machine was at least `minimumAge` before deleting it. So if a Machine went into the `Failed` phase immediately, there was at least some period in which you can catch this.

3. Don't remediate a `Failed` machine unless it has a `nodeRef`
    If a Machine failed before it got a `nodeRef` this means the configuration was invalid for some reason. Deleting the Machine is unlikely to resolve this issue. The one case where this falls down that I'm aware of is spot instances. We may want to detect spot instance creation failure and requeue rather than going failed as we presently do.

What do people think of these potential options?

**Comment by Danil-Grigorev** [comment]
`MachineHealthChecks` are evaluating `Machine` health based on the `Node` conditions. `Machine` resource here is just a bridge to the unhealthy Node resource. Option 3 seems most sane, as we should not remidiate `Machines` without a valid `nodeRef`, and we _should_ be dependent on the `NodeStartupTimeout` from `MHC` for expected `Node` creation, before removing any `Machine` resource. Including but not being limited by the `Failed` ones.

**Comment by michaelgugino** [comment]
>     3\. The one case where this falls down that I'm aware of is spot instances. We may want to detect spot instance creation failure and requeue rather than going failed as we presently do.

I want spot instances to not go failed.  They should spin until the price/capacity is available.

**Comment by zaneb** [comment]
My plan for the baremetal provider (implemented in openshift/cluster-api-provider-baremetal#113) when there is no capacity available is to:
* Retry after a delay in case capacity becomes available
* Set an `ErrorMessage `so that if the MachineSet is scaled down then the Machine with no provider goes first
* Do **not** go to the `Failed` phase
* Obviously clear the `ErrorMessage` once provisioning starts

I'm not familiar with how spot instances are handled, but it seems like something similar could work.

I like the idea of looking for a `nodeRef` to decide whether to immediately remediate, and I agree it would be a good idea to still delete the `Failed` Machine after `NodeStartupTimeout`, by just using the existing code for how long a Machine has to get to the next state if there is no Node.

**Comment by JoelSpeed** [comment]
> * Retry after a delay in case capacity becomes available
> * Set an `ErrorMessage `so that if the MachineSet is scaled down then the Machine with no provider goes first
> * Do **not** go to the `Failed` phase
> * Obviously clear the `ErrorMessage` once provisioning starts


I think this could work with spot, technically the error message field is meant for terminal errors only though. I'm not sure if the Machine Controller (presently) will set this field unless the machine has gone failed. We should check this, but it may also be able to be changed.

> good idea to still delete the `Failed` Machine after `NodeStartupTimeout`

Are we talking here about Machines that go failed because of bad config? Would that not just cause a new machine to be created with an equally bad config?

**Comment by zaneb** [comment]
> > * Retry after a delay in case capacity becomes available
> > * Set an `ErrorMessage `so that if the MachineSet is scaled down then the Machine with no provider goes first
> > * Do **not** go to the `Failed` phase
> > * Obviously clear the `ErrorMessage` once provisioning starts
> 
> I think this could work with spot, technically the error message field is meant for terminal errors only though. I'm not sure if the Machine Controller (presently) will set this field unless the machine has gone failed. We should check this, but it may also be able to be changed.

It doesn't set it at present, but you can set it directly in the actuator (in fact, in the upstream Machine API it's always the actuator that sets it, and a separate controller looks for error messages and changes the Phase). It's a slight hack, but it displays useful information to the user (the Machine is `Provisioning` but there's an error because capacity is not available) and gets the MachineSet to do the right thing (prioritise for deletion on scale-down) while allowing the actuator to retry on its own schedule, even if there is no MachineHealthCheck.

> > good idea to still delete the `Failed` Machine after `NodeStartupTimeout`
> 
> Are we talking here about Machines that go failed because of bad config?

Yes, sorry, I switched contexts without making that clear.

> Would that not just cause a new machine to be created with an equally bad config?

Indeed, unless that config has changed in the meantime, but at least it would be slow enough that you could see what was going on. I don't think there's another mechanism of making sure that when the config is fixed, any `Failed` Machines with invalid configuration errors are removed so that the MachineSet can reach its intended capacity?

**Comment by n1r1** [comment]
I'm wondering if the ProviderSpec can be invalid at some point of time but become valid after a while.
For example, in the baremetal case, maybe the image url was not reachable at the time of machine creation, but later it would be reachable.

`NodeStartupTimeout` could be too long for such scenarios on one hand, and hot looping create-delete machines is very confusing for the end user. 

So maybe we can modify the machine controller to reconcile failed machines, and call `Create()` until the machine has been successfully created. If we don't delete the machine, I believe that exponential backoff can be implemented more easily.

**Comment by JoelSpeed** [comment]
> I'm wondering if the ProviderSpec can be invalid at some point of time but become valid after a while.
For example, in the baremetal case, maybe the image url was not reachable at the time of machine creation, but later it would be reachable.

In this case I would have said that the actuator should not return an invalid configuration error if you think this is a non-terminal error and that instead, you should requeue after some time period. Is this something you'd expect to happen often? 

> Indeed, unless that config has changed in the meantime, but at least it would be slow enough that you could see what was going on. I don't think there's another mechanism of making sure that when the config is fixed, any Failed Machines with invalid configuration errors are removed so that the MachineSet can reach its intended capacity?

There isn't no, well, nothing built into MachineSets at least. If the autoscaler is involved it should detect that the MachineSet didn't bring up the new nodes and scale it back down which should remove the `Failed` machines

**Comment by n1r1** [comment]
> > I'm wondering if the ProviderSpec can be invalid at some point of time but become valid after a while.
> > For example, in the baremetal case, maybe the image url was not reachable at the time of machine creation, but later it would be reachable.
> > 
> 
> In this case I would have said that the actuator should not return an invalid configuration error if you think this is a non-terminal error and that instead, you should requeue after some time period. Is this something you'd expect to happen often?

The CAPBM actuator currently returns invalid conf error only if the fields are missing, so it matches your description.

**Comment by JoelSpeed** [comment]
@mshitrit This is relevant to the conversation we had last week

**Comment by zaneb** [comment]
Looks like this will be addressed by #814 (openshift/enhancements#673).
