### ISSUE TITLE
Dropping Container Linux?

### ISSUE THREAD

**Issue by wking** [openshift/machine-api-operator#84]
The installer dropped support for Container Linux in openshift/installer#221.  But there appear to still be some assumptions about Container Linux in this repository (e.g. [here][1]).  Is there a plan for dropping that?  Or am I just misunderstanding something about how this operator fits into the cluster?

[1]: https://github.com/openshift/machine-api-operator/blob/f2689d525af210706c152075a7570cd60855999d/pkg/render/config.go#L39-L40

**Comment by enxebre** [comment]
The filter assumptions are actually not applying as the ami id is passed. Yes, we might wanna change to rhcos filters or just expect always an id

**Comment by enxebre** [comment]
Closing this as machines definition lives on the installer now
For reference:
openshift/installer#468
https://github.com/openshift/installer/tree/master/pkg/asset/machines
